<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateEncuestasTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('encuestas', function (Blueprint $table) {
            $table->bigIncrements('id');
        //
$table->string("accesos")->nullable();
$table->string("accesos_detalle")->nullable();
$table->string("acompanan_nino")->nullable();
$table->string("actividad_extracurricular")->nullable();
$table->string("actividad_extracurricular_detalle")->nullable();
$table->string("actividad_fisica_aclaracion")->nullable();
$table->string("actividad_fisica_inicial_dias")->nullable();
$table->string("actividad_fisica_inicial_minutos")->nullable();
$table->string("actividad_fisica_primer_ciclo_dias")->nullable();
$table->string("actividad_fisica_primer_ciclo_minutos")->nullable();
$table->string("actividad_fisica_secundaria_ciclo_dias")->nullable();
$table->string("actividad_fisica_secundaria_ciclo_minutos")->nullable();
$table->string("actividad_fisica_segundo_ciclo_dias")->nullable();
$table->string("actividad_fisica_segundo_ciclo_minutos")->nullable();
$table->string("agua_con_sin_gas")->nullable();
$table->string("agua_corriente")->nullable();
$table->string("agua_estrategia_segura")->nullable();
$table->string("agua_presentacion")->nullable();
$table->string("agua_saborizada")->nullable();
$table->string("agua_saborizada_ligth")->nullable();
$table->string("agua_segura_beber")->nullable();
$table->string("agua_segura_cepillarse_dientes")->nullable();
$table->string("agua_segura_otro_detalle")->nullable();
$table->string("agua_segura_cocinar")->nullable();
$table->string("agua_segura_hacer_hielo")->nullable();
$table->string("agua_segura_infusiones")->nullable();
$table->string("agua_segura_lavar_alimentos")->nullable();
$table->string("alfajores_obleas")->nullable();
$table->string("alfajores_obles_de_arroz")->nullable();
$table->string("alimento_tradicional")->nullable();
$table->string("alimento_tradicional_detalle")->nullable();
$table->string("alimento_tradicional_frecuencia")->nullable();
$table->string("alumna_embarazada")->nullable();
$table->string("apto_medico")->nullable();
$table->string("apto_medico_detalle_no")->nullable();
$table->string("ayudantes")->nullable();
$table->string("ayudantes_capacitados")->nullable();
$table->string("ayudantes_capacitados_tematica")->nullable();
$table->string("barras_cereal")->nullable();
$table->string("barras_cereales")->nullable();
$table->string("bebedores_cantidad")->nullable();
$table->string("bebidad_energizantes")->nullable();
$table->string("bebidas_alcohol")->nullable();
$table->string("bizcochos_grasa")->nullable();
$table->string("budines")->nullable();
$table->string("capacitacion_comercio")->nullable();
$table->string("capacitacion_comercio_detalle")->nullable();
$table->string("careales_azucarados")->nullable();
$table->string("cargo_informante")->nullable();
$table->string("cargo_otro")->nullable();
$table->string("categoria_comercializacion")->nullable();
$table->string("cereales_sin_azucar")->nullable();
$table->string("chicles_caramelos")->nullable();
$table->string("chocolates_con_azucar")->nullable();
$table->string("clase_extracurricular")->nullable();
$table->string("clase_extracurricular_detalle")->nullable();
$table->string("clase_mix")->nullable();
$table->string("clase_mix_nivel_educatio")->nullable();
$table->string("comercializacion_inmediacion")->nullable();
$table->string("comercializacion_inmediacion_detalle")->nullable();
$table->string("compra_insumo")->nullable();
$table->string("compra_may_men")->nullable();
$table->string("compra_may_men_detalle")->nullable();
$table->string("coordinador")->nullable();
$table->string("copetin")->nullable();
$table->string("ctrl_sanitario")->nullable();
$table->string("ctrl_sanitario_detalle")->nullable();
$table->string("detalle_cuantos_alumnos")->nullable();
$table->string("detalle_exige_niveles")->nullable();
$table->string("detalle_exigencias")->nullable();
$table->string("detalle_normativa")->nullable();
$table->string("detalle_porcentajes_alumnos_primaria")->nullable();
$table->string("detalle_porcentajes_alumnos_secundaria")->nullable();
$table->string("durante_comida_agua_saborizada")->nullable();
$table->string("durante_comida_agua_segura")->nullable();
$table->string("durante_comida_gaseosa_azucarada")->nullable();
$table->string("durante_comida_jugo_fruta_fresa")->nullable();
$table->string("durante_comida_jugo_industrial_para_consumir")->nullable();
$table->string("durante_comida_jugo_industrial_para_reconstituir")->nullable();
$table->string("empanadas_al_horno_fiambre")->nullable();
$table->string("empanadas_al_horno_verdura")->nullable();
$table->string("empanadas_fritas")->nullable();
$table->string("encargado_alimento")->nullable();
$table->string("encuestador")->nullable();
$table->string("enfoque_inclusivo")->nullable();
$table->string("enfoque_inclusivo_detalle")->nullable();
$table->string("ensalada_frutas")->nullable();
$table->string("ensalada_vegetales")->nullable();
$table->string("espacio_activ_fisica")->nullable();
$table->string("espacio_activ_fisica_detalle")->nullable();
$table->string("espacio_lactancia")->nullable();
$table->string("espacio_movimiento_espontaneo")->nullable();
$table->string("espacio_movimiento_espontaneo_detalle")->nullable();
$table->string("establecimiento")->nullable();
$table->string("evaluacion_aptitud")->nullable();
$table->string("evaluacion_aptitud_detalle_no")->nullable();
$table->string("facturas")->nullable();
$table->string("foto_area_elaboracion")->nullable();
$table->string("foto_bebedero")->nullable();
$table->string("foto_comedor")->nullable();
$table->string("foto_menu")->nullable();
$table->string("foto_plato_almuerzo")->nullable();
$table->string("foto_plato_desayuno")->nullable();
$table->string("foto_plato_merienda")->nullable();
$table->string("foto_servicio_alimentos")->nullable();
$table->string("frutas_disecadas")->nullable();
$table->string("frutas_frescas")->nullable();
$table->string("frutos_secos")->nullable();
$table->string("galletas_arroz")->nullable();
$table->string("galletas_dulces")->nullable();
$table->string("galletas_dulces_sin_relleno")->nullable();
$table->string("galletitas_cereal")->nullable();
$table->string("galletitas_de_agua")->nullable();
$table->string("gaseosas")->nullable();
$table->string("gaseosas_light")->nullable();
$table->string("golosinas_sin_azucar")->nullable();
$table->string("habitos_comida")->nullable();
$table->string("hamburguesas_de_carne")->nullable();
$table->string("hay_bebedero")->nullable();
$table->string("helados")->nullable();
$table->string("huerta")->nullable();
$table->string("incentivo_consumo")->nullable();
$table->string("incentivo_consumo_detalle")->nullable();
$table->string("informe_menu")->nullable();
$table->string("jugo_de_frutas")->nullable();
$table->string("jugos_industrializados")->nullable();
$table->string("latitud")->nullable();
$table->string("leche_descremada")->nullable();
$table->string("licuado_frutas")->nullable();
$table->string("localidad")->nullable();
$table->string("longitud")->nullable();
$table->string("lugar_almuerzo")->nullable();
$table->string("lugar_almuerzo_otros")->nullable();
$table->string("lugar_bebedero_banio")->nullable();
$table->string("lugar_bebedero_espacio_comun")->nullable();
$table->string("lugar_bebedero_otro")->nullable();
$table->string("lugar_bebedero_patio")->nullable();
$table->string("lugar_desayuno_merienda")->nullable();
$table->string("lugar_desayuno_merienda_otros")->nullable();
$table->string("lugar_fumador")->nullable();
$table->string("lugar_otro")->nullable();
$table->string("lugar_preparacion_comida")->nullable();
$table->string("materia_especifica_existente_detalle")->nullable();
$table->string("matricula_cantitad")->nullable();
$table->string("menu_especial")->nullable();
$table->string("menu_especial_otro")->nullable();
$table->string("menu_vista")->nullable();
$table->string("nino_cepillan")->nullable();
$table->string("nino_lavan")->nullable();
$table->string("nomynum_establecimiento")->nullable();
$table->string("num_docente_nodocente")->nullable();
$table->string("observaciones")->nullable();
$table->string("obtencion_dato")->nullable();
$table->string("panchos")->nullable();
$table->string("pantallas_vista")->nullable();
$table->string("papas_fritas_naturales")->nullable();
$table->string("permanencia_desde_almuerzo")->nullable();
$table->string("permanencia_desde_desayuno_merienda")->nullable();
$table->string("permanencia_desde_otro")->nullable();
$table->string("permanencia_duracion_almuerzo")->nullable();
$table->string("permanencia_duracion_desayuno_merienda")->nullable();
$table->string("permanencia_duracion_otro")->nullable();
$table->string("permanencia_hasta_almuerzo")->nullable();
$table->string("permanencia_hasta_desayuno_merienda")->nullable();
$table->string("permanencia_hasta_otro")->nullable();
$table->string("permanencia_otro")->nullable();
$table->string("persona_fumando")->nullable();
$table->string("pizza_con_verdura")->nullable();
$table->string("pizzas_sin_verdura")->nullable();
$table->string("postres_lacteos")->nullable();
$table->string("postres_lacteos_sin_azucar")->nullable();
$table->string("prestacion_servicio_almuerzo")->nullable();
$table->string("prestacion_servicio_desayuno")->nullable();
$table->string("prestacion_servicio_merienda")->nullable();
$table->string("procedimiento_limpieza_almacen")->nullable();
$table->string("profe_titulo")->nullable();
$table->string("profe_titulo_detalle_no")->nullable();
$table->string("programas_ean")->nullable();
$table->string("prome_tematicas_alimentacion_activida_fisica")->nullable();
$table->string("promo_salud")->nullable();
$table->string("promo_salud_detalle")->nullable();
$table->string("promo_tematicas_alimentacion_consumo_alcohol")->nullable();
$table->string("promo_tematicas_alimentacion_consumo_sal")->nullable();
$table->string("promo_tematicas_alimentacion_consumo_tabaco")->nullable();
$table->string("promo_tematicas_alimentacion_saludable")->nullable();
$table->string("promo_tematicas_observaciones")->nullable();
$table->string("promueve_transporte_activo")->nullable();
$table->string("promueve_transporte_activo_detalle")->nullable();
$table->string("promueven_espacio_lactiancia")->nullable();
$table->string("promueven_espacio_lactiancia_detalle")->nullable();
$table->string("propuestas_sociocultural")->nullable();
$table->string("propuestas_sociocultural_detalle")->nullable();
$table->string("publicidad_alimento")->nullable();
$table->string("publicidad_alimento_fachada")->nullable();
$table->string("publicidad_alimento_menu")->nullable();
$table->string("publicidad_alimento_mesa")->nullable();
$table->string("publicidad_alimento_mobiliario")->nullable();
$table->string("publicidad_alimento_otro")->nullable();
$table->string("publicidad_alimento_paredes")->nullable();
$table->string("punto_comercializacion")->nullable();
$table->string("rama")->nullable();
$table->string("recomendaciones_gapa")->nullable();
$table->string("recomendaciones_macro_micronutrientes")->nullable();
$table->string("sal_libre")->nullable();
$table->string("sal_presentacion_otro_detalle")->nullable();
$table->string("sal_presentacion_sal_baja_sodio")->nullable();
$table->string("sal_presentacion_salero")->nullable();
$table->string("sal_presentacion_sobres")->nullable();
$table->string("salon_comedor")->nullable();
$table->string("sandwich_de_milanesa")->nullable();
$table->string("sandwich_embutido")->nullable();
$table->string("sandwich_magro")->nullable();
$table->string("semillas_sin_sal")->nullable();
$table->string("silla_mesa")->nullable();
$table->string("sopas_instantaneas")->nullable();
$table->string("supervicion_menu")->nullable();
$table->string("tarta_de_verdura")->nullable();
$table->string("timestamp")->nullable();
$table->string("tipo_gestion_estructurada_almuerzo")->nullable();
$table->string("tipo_gestion_estructurada_desayuno")->nullable();
$table->string("tipo_gestion_estructurada_merienda")->nullable();
$table->string("tipo_jornada")->nullable();
$table->string("tortas_con_crema")->nullable();
$table->string("userid")->nullable();
$table->string("utensilios")->nullable();
$table->string("vestimenta")->nullable();
$table->string("yogur_entero")->nullable();
$table->string("yogures_sin_azucar")->nullable();

$table->string("hash")->nullable();
        //
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('encuestas');
    }
}
