<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateEncuestasTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('encuestas', function (Blueprint $table) {
            $table->bigIncrements('id');
        //
$table->text("accesos")->nullable();
$table->text("accesos_detalle")->nullable();
$table->text("acompanan_nino")->nullable();
$table->text("actividad_extracurricular")->nullable();
$table->text("actividad_extracurricular_detalle")->nullable();
$table->text("actividad_fisica_aclaracion")->nullable();
$table->text("actividad_fisica_inicial_dias")->nullable();
$table->text("actividad_fisica_inicial_minutos")->nullable();
$table->text("actividad_fisica_primer_ciclo_dias")->nullable();
$table->text("actividad_fisica_primer_ciclo_minutos")->nullable();
$table->text("actividad_fisica_secundaria_ciclo_dias")->nullable();
$table->text("actividad_fisica_secundaria_ciclo_minutos")->nullable();
$table->text("actividad_fisica_segundo_ciclo_dias")->nullable();
$table->text("actividad_fisica_segundo_ciclo_minutos")->nullable();
$table->text("agua_con_sin_gas")->nullable();
$table->text("agua_corriente")->nullable();
$table->text("agua_estrategia_segura")->nullable();
$table->text("agua_presentacion")->nullable();
$table->text("agua_saborizada")->nullable();
$table->text("agua_saborizada_ligth")->nullable();
$table->text("agua_segura_beber")->nullable();
$table->text("agua_segura_cepillarse_dientes")->nullable();
$table->text("agua_segura_otro_detalle")->nullable();
$table->text("agua_segura_cocinar")->nullable();
$table->text("agua_segura_hacer_hielo")->nullable();
$table->text("agua_segura_infusiones")->nullable();
$table->text("agua_segura_lavar_alimentos")->nullable();
$table->text("alfajores_obleas")->nullable();
$table->text("alfajores_obles_de_arroz")->nullable();
$table->text("alimento_tradicional")->nullable();
$table->text("alimento_tradicional_detalle")->nullable();
$table->text("alimento_tradicional_frecuencia")->nullable();
$table->text("alumna_embarazada")->nullable();
$table->text("apto_medico")->nullable();
$table->text("apto_medico_detalle_no")->nullable();
$table->text("ayudantes")->nullable();
$table->text("ayudantes_capacitados")->nullable();
$table->text("ayudantes_capacitados_tematica")->nullable();
$table->text("barras_cereal")->nullable();
$table->text("barras_cereales")->nullable();
$table->text("bebedores_cantidad")->nullable();
$table->text("bebidad_energizantes")->nullable();
$table->text("bebidas_alcohol")->nullable();
$table->text("bizcochos_grasa")->nullable();
$table->text("budines")->nullable();
$table->text("capacitacion_comercio")->nullable();
$table->text("capacitacion_comercio_detalle")->nullable();
$table->text("careales_azucarados")->nullable();
$table->text("cargo_informante")->nullable();
$table->text("cargo_otro")->nullable();
$table->text("categoria_comercializacion")->nullable();
$table->text("cereales_sin_azucar")->nullable();
$table->text("chicles_caramelos")->nullable();
$table->text("chocolates_con_azucar")->nullable();
$table->text("clase_extracurricular")->nullable();
$table->text("clase_extracurricular_detalle")->nullable();
$table->text("clase_mix")->nullable();
$table->text("clase_mix_nivel_educatio")->nullable();
$table->text("comercializacion_inmediacion")->nullable();
$table->text("comercializacion_inmediacion_detalle")->nullable();
$table->text("compra_insumo")->nullable();
$table->text("compra_may_men")->nullable();
$table->text("compra_may_men_detalle")->nullable();
$table->text("coordinador")->nullable();
$table->text("copetin")->nullable();
$table->text("ctrl_sanitario")->nullable();
$table->text("ctrl_sanitario_detalle")->nullable();
$table->text("detalle_cuantos_alumnos")->nullable();
$table->text("detalle_exige_niveles")->nullable();
$table->text("detalle_exigencias")->nullable();
$table->text("detalle_normativa")->nullable();
$table->text("detalle_porcentajes_alumnos_primaria")->nullable();
$table->text("detalle_porcentajes_alumnos_secundaria")->nullable();
$table->text("durante_comida_agua_saborizada")->nullable();
$table->text("durante_comida_agua_segura")->nullable();
$table->text("durante_comida_gaseosa_azucarada")->nullable();
$table->text("durante_comida_jugo_fruta_fresa")->nullable();
$table->text("durante_comida_jugo_industrial_para_consumir")->nullable();
$table->text("durante_comida_jugo_industrial_para_reconstituir")->nullable();
$table->text("empanadas_al_horno_fiambre")->nullable();
$table->text("empanadas_al_horno_verdura")->nullable();
$table->text("empanadas_fritas")->nullable();
$table->text("encargado_alimento")->nullable();
$table->text("encuestador")->nullable();
$table->text("enfoque_inclusivo")->nullable();
$table->text("enfoque_inclusivo_detalle")->nullable();
$table->text("ensalada_frutas")->nullable();
$table->text("ensalada_vegetales")->nullable();
$table->text("espacio_activ_fisica")->nullable();
$table->text("espacio_activ_fisica_detalle")->nullable();
$table->text("espacio_lactancia")->nullable();
$table->text("espacio_movimiento_espontaneo")->nullable();
$table->text("espacio_movimiento_espontaneo_detalle")->nullable();
$table->text("establecimiento")->nullable();
$table->text("evaluacion_aptitud")->nullable();
$table->text("evaluacion_aptitud_detalle_no")->nullable();
$table->text("facturas")->nullable();
$table->text("foto_area_elaboracion")->nullable();
$table->text("foto_bebedero")->nullable();
$table->text("foto_comedor")->nullable();
$table->text("foto_menu")->nullable();
$table->text("foto_plato_almuerzo")->nullable();
$table->text("foto_plato_desayuno")->nullable();
$table->text("foto_plato_merienda")->nullable();
$table->text("foto_servicio_alimentos")->nullable();
$table->text("frutas_disecadas")->nullable();
$table->text("frutas_frescas")->nullable();
$table->text("frutos_secos")->nullable();
$table->text("galletas_arroz")->nullable();
$table->text("galletas_dulces")->nullable();
$table->text("galletas_dulces_sin_relleno")->nullable();
$table->text("galletitas_cereal")->nullable();
$table->text("galletitas_de_agua")->nullable();
$table->text("gaseosas")->nullable();
$table->text("gaseosas_light")->nullable();
$table->text("golosinas_sin_azucar")->nullable();
$table->text("habitos_comida")->nullable();
$table->text("hamburguesas_de_carne")->nullable();
$table->text("hay_bebedero")->nullable();
$table->text("helados")->nullable();
$table->text("huerta")->nullable();
$table->text("incentivo_consumo")->nullable();
$table->text("incentivo_consumo_detalle")->nullable();
$table->text("informe_menu")->nullable();
$table->text("jugo_de_frutas")->nullable();
$table->text("jugos_industrializados")->nullable();
$table->text("latitud")->nullable();
$table->text("leche_descremada")->nullable();
$table->text("licuado_frutas")->nullable();
$table->text("localidad")->nullable();
$table->text("longitud")->nullable();
$table->text("lugar_almuerzo")->nullable();
$table->text("lugar_almuerzo_otros")->nullable();
$table->text("lugar_bebedero_banio")->nullable();
$table->text("lugar_bebedero_espacio_comun")->nullable();
$table->text("lugar_bebedero_otro")->nullable();
$table->text("lugar_bebedero_patio")->nullable();
$table->text("lugar_desayuno_merienda")->nullable();
$table->text("lugar_desayuno_merienda_otros")->nullable();
$table->text("lugar_fumador")->nullable();
$table->text("lugar_otro")->nullable();
$table->text("lugar_preparacion_comida")->nullable();
$table->text("materia_especifica_existente_detalle")->nullable();
$table->text("matricula_cantitad")->nullable();
$table->text("menu_especial")->nullable();
$table->text("menu_especial_otro")->nullable();
$table->text("menu_vista")->nullable();
$table->text("nino_cepillan")->nullable();
$table->text("nino_lavan")->nullable();
$table->text("nomynum_establecimiento")->nullable();
$table->text("num_docente_nodocente")->nullable();
$table->text("observaciones")->nullable();
$table->text("obtencion_dato")->nullable();
$table->text("panchos")->nullable();
$table->text("pantallas_vista")->nullable();
$table->text("papas_fritas_naturales")->nullable();
$table->text("permanencia_desde_almuerzo")->nullable();
$table->text("permanencia_desde_desayuno_merienda")->nullable();
$table->text("permanencia_desde_otro")->nullable();
$table->text("permanencia_duracion_almuerzo")->nullable();
$table->text("permanencia_duracion_desayuno_merienda")->nullable();
$table->text("permanencia_duracion_otro")->nullable();
$table->text("permanencia_hasta_almuerzo")->nullable();
$table->text("permanencia_hasta_desayuno_merienda")->nullable();
$table->text("permanencia_hasta_otro")->nullable();
$table->text("permanencia_otro")->nullable();
$table->text("persona_fumando")->nullable();
$table->text("pizza_con_verdura")->nullable();
$table->text("pizzas_sin_verdura")->nullable();
$table->text("postres_lacteos")->nullable();
$table->text("postres_lacteos_sin_azucar")->nullable();
$table->text("prestacion_servicio_almuerzo")->nullable();
$table->text("prestacion_servicio_desayuno")->nullable();
$table->text("prestacion_servicio_merienda")->nullable();
$table->text("procedimiento_limpieza_almacen")->nullable();
$table->text("profe_titulo")->nullable();
$table->text("profe_titulo_detalle_no")->nullable();
$table->text("programas_ean")->nullable();
$table->text("prome_tematicas_alimentacion_activida_fisica")->nullable();
$table->text("promo_salud")->nullable();
$table->text("promo_salud_detalle")->nullable();
$table->text("promo_tematicas_alimentacion_consumo_alcohol")->nullable();
$table->text("promo_tematicas_alimentacion_consumo_sal")->nullable();
$table->text("promo_tematicas_alimentacion_consumo_tabaco")->nullable();
$table->text("promo_tematicas_alimentacion_saludable")->nullable();
$table->text("promo_tematicas_observaciones")->nullable();
$table->text("promueve_transporte_activo")->nullable();
$table->text("promueve_transporte_activo_detalle")->nullable();
$table->text("promueven_espacio_lactiancia")->nullable();
$table->text("promueven_espacio_lactiancia_detalle")->nullable();
$table->text("propuestas_sociocultural")->nullable();
$table->text("propuestas_sociocultural_detalle")->nullable();
$table->text("publicidad_alimento")->nullable();
$table->text("publicidad_alimento_fachada")->nullable();
$table->text("publicidad_alimento_menu")->nullable();
$table->text("publicidad_alimento_mesa")->nullable();
$table->text("publicidad_alimento_mobiliario")->nullable();
$table->text("publicidad_alimento_otro")->nullable();
$table->text("publicidad_alimento_paredes")->nullable();
$table->text("punto_comercializacion")->nullable();
$table->text("rama")->nullable();
$table->text("recomendaciones_gapa")->nullable();
$table->text("recomendaciones_macro_micronutrientes")->nullable();
$table->text("sal_libre")->nullable();
$table->text("sal_presentacion_otro_detalle")->nullable();
$table->text("sal_presentacion_sal_baja_sodio")->nullable();
$table->text("sal_presentacion_salero")->nullable();
$table->text("sal_presentacion_sobres")->nullable();
$table->text("salon_comedor")->nullable();
$table->text("sandwich_de_milanesa")->nullable();
$table->text("sandwich_embutido")->nullable();
$table->text("sandwich_magro")->nullable();
$table->text("semillas_sin_sal")->nullable();
$table->text("silla_mesa")->nullable();
$table->text("sopas_instantaneas")->nullable();
$table->text("supervicion_menu")->nullable();
$table->text("tarta_de_verdura")->nullable();
$table->text("timestamp")->nullable();
$table->text("tipo_gestion_estructurada_almuerzo")->nullable();
$table->text("tipo_gestion_estructurada_desayuno")->nullable();
$table->text("tipo_gestion_estructurada_merienda")->nullable();
$table->text("tipo_jornada")->nullable();
$table->text("tortas_con_crema")->nullable();
$table->text("userid")->nullable();
$table->text("utensilios")->nullable();
$table->text("vestimenta")->nullable();
$table->text("yogur_entero")->nullable();
$table->text("yogures_sin_azucar")->nullable();
$table->date("fecha_realizacion")->nullable();
$table->text("hash")->nullable();
        //
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('encuestas');
    }
}
